<#import "/macros/template.ftlh" as template/>
<@template.render pagetitle="Cras vel egestas est!">
	<h2>Lorem ipsum dolor sit amet</h2>
	<p>Nullam quis risus eget <a href="#">urna mollis ornare</a> vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula.</p>
	<h2>Neque porro quisquam est qui dolorem ipsum</h2>
	<p>Vestibulum urna magna, scelerisque a porttitor in, dignissim sit amet nunc. Aliquam erat volutpat. Nam id fermentum diam. Proin imperdiet diam tristique venenatis porta. Suspendisse fringilla, lacus sed semper ultricies, est dui tempus sem, non feugiat neque ex ullamcorper erat. Praesent sit amet enim bibendum, ultricies nisl vel, pellentesque augue. Vivamus hendrerit hendrerit vulputate. Praesent pulvinar laoreet scelerisque. </p>
	<h3>Nam ultrices ut tortor eu vulputate</h3>
	<p>Sed id aliquet nibh, ac feugiat est. Nam augue justo, mollis volutpat neque nec, ultrices vulputate sapien. Cras fringilla hendrerit lorem a molestie.</p>
</@template.render>