<div class="col-lg-3 col-md-3 col-sm-4">
	<div class="list-group">
		<a class="list-group-item" href="${contextroot}"><i class="fa fa-home fa-fw" aria-hidden="true"></i> Home</a>
		<a class="list-group-item" href="#"><i class="fa fa-users fa-fw" aria-hidden="true"></i> Your Family</a>
		<a class="list-group-item" href="#"><i class="fa fa-shopping-basket fa-fw" aria-hidden="true"></i> Reward shop</a>
	</div>
</div>