INSERT INTO ROLE (ID, DATE_CREATED, DATE_UPDATED, NAME) VALUES (1, CURRENT_TIMESTAMP, null, 'ROLE_ADMIN');
INSERT INTO ROLE (ID, DATE_CREATED, DATE_UPDATED, NAME) VALUES (2, CURRENT_TIMESTAMP, null, 'ROLE_USER');

INSERT INTO USER (ID, DATE_CREATED, DATE_UPDATED, USERNAME, PASSWORD, ENABLED, VALIDATED) VALUES (1, CURRENT_TIMESTAMP, null, 'greg.baker.bsc@gmail.com', '$2a$10$Stextcggi2pPAMpBC3Yt7ucSAFvt6F/W4gmQcHOgIIFbcHS9wq.l6', TRUE, TRUE);

INSERT INTO USER_ROLES (USERS_ID, ROLES_ID) VALUES (1, 1);
INSERT INTO USER_ROLES (USERS_ID, ROLES_ID) VALUES (1, 2);